version: '3'

services:
  webserver_service:
    build: ./webserver
    image: webserver_service
    container_name: webserver_service
    volumes:
      - ./webserver:/app
      - ./DATA:/app/DATA
      - ./DATA2:/app/DATA2
    ports:
      - 5000:5000
    depends_on:
      - redis_server
  worker:
    image: webserver_service
    container_name: webworker_service
    command: python redis_worker.py
    volumes:
    - ./webserver:/app
    depends_on:
      - redis_server
  client-service:
    build: ./client
    image: client_service
    container_name: client_service
    volumes:
      - ./client:/app
    ports:
      - 5001:5001
    depends_on:
      - redis_server
  redis_server:
    image: redis:5.0.7-alpine
    container_name: redis_server
    ports:
      - 6379:6379
